### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Random improvements extracted from #253:
- Fixed some style issues
- Removed redundant imports
- Minimized `try` scope and removed redundant debug log

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@ajoberstar mind taking a look?

**Comment by SUPERCILEX** [comment]
@ajoberstar mind taking a look?

**Comment by SUPERCILEX** [comment]
@ajoberstar bump

**Comment by ajoberstar** [comment]
Sorry for the delay. I'm going to hold off on this one for the moment. At some point I'm going to try to get the Spotless plugin configured correctly to reformat the code, which should address the majority of what you provided here and enforce it in the future.

**Comment by SUPERCILEX** [comment]
See https://github.com/ajoberstar/grgit/pull/253#issuecomment-427240359

**Comment by ajoberstar** [comment]
As mentioned in #253, thanks for your work on these changes, however, I'm not interested in pulling in this cleanup. There's a lot in this PR and there were a couple changes I wasn't in favor of. If I ever get the time to automate the formatting, I'll do something similar, but until then I'd like to avoid formatting changes.

**Pull request closed without merging**
