### PR TITLE
Relating to #339, lock dependency to version 5 for jgit.

### PR DESCRIPTION
**Pull request by hborham**

### CODE REVIEW

**Comment by hborham** [comment]
Can you please review and release as 4.1.1?

**Comment by hborham** [comment]
https://github.com/ajoberstar/grgit/issues/339

**Comment by Crunkle** [comment]
This project uses [dependency locking](https://docs.gradle.org/current/userguide/dependency_locking.html) and [explicitly requests 5.9](https://github.com/ajoberstar/grgit/blob/ccbe02b2288817d145cbe89a4ef18e454965ad4f/grgit-gradle/gradle/dependency-locks/compileClasspath.lockfile) in the lock files. I think this may be a configuration issue when publishing the plugin, not an issue with the `latest.release` dependencies.

**Comment by hborham** [comment]
Curious  now.  We see the pom as `<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  
  
  
  
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.ajoberstar.grgit</groupId>
  <artifactId>grgit-core</artifactId>
  <version>4.1.0</version>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.jgit</groupId>
      <artifactId>org.eclipse.jgit</artifactId>
      <version>RELEASE</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>`

**Comment by gotson** [comment]
Looks like even when changing this, there is still version 6 being brought by the `org.ajoberstar.reckon` Gradle plugin which [uses](https://github.com/ajoberstar/reckon/blob/a1f5fe9e2e3cc6ef18f9db3457e98d2843d27176/build.gradle#L43) `[5.0,6.0)` for jgit.

**Comment by hborham** [comment]
> Looks like even when changing this, there is still version 6 being brought by the `org.ajoberstar.reckon` Gradle plugin which [uses](https://github.com/ajoberstar/reckon/blob/a1f5fe9e2e3cc6ef18f9db3457e98d2843d27176/build.gradle#L43) `[5.0,6.0)` for jgit.

Good catch, I just added another commit to take care of the buildscript section.  I think this should be reverted later but seems like a necessary evil due to the pom issue this PR is trying to address

**Comment by ajoberstar** [comment]
Used a different approach in #344

**Pull request closed without merging**
