### PR TITLE
Adds samples

### LINKED ISSUE #204: Please add examples of git clone in Gradle 4.3
Hi,
I'm new to Gradle. I've found this plugin referred to in several SO answers and in the [documentation](http://ajoberstar.org/grgit/grgit-clone.html) but have not come across a simple working example that I can run and see working. Most seem to be using older versions of Gradle. Would you please add documentation that uses an example gradle file using this plugin?

### PR DESCRIPTION
**Pull request by stebbi**
Hi there, I picked one of your issues as an example for me to familiarize myself with the Github pull requests workflow, perhaps these samples can be useful for someone. Thanks for the library - I've used if a fair bit and it is very nice. Cheers - Stefan

### CODE REVIEW

**Comment by ajoberstar** [comment]
Again, sorry for the delay and thanks for the interest in contributing. I'm still pondering this one, since I'm not sure how I want to support samples. Main issue being ensuring they still work as changes are made to the library. As a manual step, there's a likelihood I'll forget to run them again.

**Comment by brambolt** [comment]
Hi, yes, understood, I have the same problem in my projects - I tend to like samples as the quickest way to pick up a new tool, so I've dealt with this by extending my builds to finalize the test task by running the samples. I don't know if that would work for you but, I do it roughly like so: 

1. Master build includes a statement similar to `test.finalizedBy(':samples:runAll')
1. Samples directory contains `build.gradle` with individual tasks for the samples
1. The samples build file also defines the `runAll` task with dependencies on the individual sample tasks

I also tend to like to have self-checks in each sample, this also serves as a way of document what exactly the sample is trying to do. 

This is only a few lines of code, let me know if you'd like me to add that to the PR. The pattern is a little bit pedestrian maybe, but very simple, and has worked out alright for me.

**Comment by stebbi** [comment]
Hi, yes, understood, I have the same problem in my projects - I tend to like samples as the quickest way to pick up a new tool, so I've dealt with this by extending my builds to finalize the test task by running the samples. I don't know if that would work for you but, I do it roughly like so:

1. Master build includes a statement similar to `test.finalizedBy(':samples:runAll')
2. Samples directory contains build.gradle with individual tasks for the samples
3. The samples build file also defines the runAll task with dependencies on the individual sample tasks

I also tend to like to have self-checks in each sample, this also serves as a way of document what exactly the sample is trying to do. Once those are included, the master build effectively checks that the samples still work. 

This is only a few lines of code, let me know if you'd like me to add that to the PR. The pattern is a little bit pedestrian maybe, but very simple, and has worked out alright for me.

**Comment by rusefillc** [comment]
@stebbi poke :)

**Comment by ajoberstar** [comment]
Apologies for not finding a way to make this work, but given the current state of the project adding samples will just increase the maintenance burden, so I'm going to close this. Thank you for the initial effort!

**Pull request closed without merging**
