### PR TITLE
Implement --contains flag for branch list

### PR DESCRIPTION
**Pull request by nesterov-n**
Hello. 

I implemented '--contains' param for branch list command.

### CODE REVIEW

**Comment by ajoberstar** [comment]
Thanks for putting this together. One change I think would be benficial is making `contains` an `Object`, so it could be a Grgit `Commit` instance or some other representation of a revision. If you look at [TagAddOp](https://github.com/ajoberstar/grgit/blob/master/src/main/groovy/org/ajoberstar/grgit/operation/TagAddOp.groovy#L100) I'm using that pattern for the `pointsTo` object (and use the `toRevisionString` method to convert it back to a string).

**Comment by nesterov-n** [comment]
@ajoberstar Done

**Comment by ajoberstar** [comment]
Great! Thanks again.

**Comment by nesterov-n** [comment]
@ajoberstar When do you plan release new version of your lib? I really need this feature for my build system :)

**Comment by ajoberstar** [comment]
1.6.0-rc.1 is out now

**Comment by nesterov-n** [comment]
Great! Thanks a lot

**Pull request merged**
