### PR TITLE
Add final check whether a Git repo was found

### PR DESCRIPTION
**Pull request by criztovyl**
See #128

### CODE REVIEW

**Comment by ajoberstar** [comment]
Thanks for the PR. It's probably worth creating some tests for this. Testing both `dir` and `currentDir` options. I'm wondering if we need to catch it in that other branch too.

**Comment by criztovyl** [comment]
The other `if`-Branch isn't FileRepositoryBuilder (at least not directly), I think it's differen there, maybe already handled somewhere else.
I'll write some tests :)

**Comment by ajoberstar** [comment]
Sounds good

**Comment by criztovyl** [comment]
What's about that test below, shouldn't this already fail?
https://github.com/ajoberstar/grgit/blob/master/src/test/groovy/org/ajoberstar/grgit/operation/OpenOpSpec.groovy#L42

**Comment by criztovyl** [comment]
It's a single test only for now, need more? :)

**Comment by ajoberstar** [comment]
This looks good. Thanks again!

**Pull request merged**
