### PR TITLE
Add show operation

### PR DESCRIPTION
**Pull request by Odinodin**
- the show operation let's you see changes made in a commit. This includes list of changed files, types of change and the raw diff string for each change.

### CODE REVIEW

**Comment by ajoberstar** [comment]
Thanks for the interest in contributing! I haven't reviewed this super-close yet, but the code looks good. 

Mainly, I just have a question about the use case. What applications do you have for the show op through Groovy code? So far, I've avoided including things that don't seem to provide programmatic benefit (for example, resolving merge conflicts) and/or non-porcelain commands. I'm not saying this falls in one of those categories, but it seems a little closer to out of scope than most of the current operations.

If the use case makes sense, I'll probably have this released within the next week.

**Comment by Odinodin** [comment]
My use case was that I have a gradle build where I have a task that relies on what changed in the previous commit. Basically I detect which sub-directories had changes before starting a time-consuming process for each of the changed sub-directories. So I needed a way to retrieve the list of changed files.

I totally understand if you think this is a fringe use-case for this library.

**Comment by ajoberstar** [comment]
It may still be a fringe use case, but that does sound like it's in the wheelhouse still. Do you just need a list of the directories/files that changed, or do you need the diffs themselves? I could see dropping the diffStrings, but keeping the remainder of what your proposed originally. Let me know either way and I can started on merging.

**Comment by Odinodin** [comment]
The important part is the list of changed files, not the actual diffs. I just added them because it was easy, so I don't mind if you take that away.

**Comment by ajoberstar** [comment]
I have this merged in now. I reworked the structure of `CommitDiff` to line up with `Status`, but I think it still gives you all of the information you needed.

Let me know if you have any other thoughts on this. I'll hold off on releasing the final 1.2.0 for a bit to give you a chance to take a look.

**Comment by Odinodin** [comment]
Just had a look, looks great. Thanks for pulling this in.

**Comment by ajoberstar** [comment]
Thanks for contributing! Just released final 1.2.0. Available in Bintray, should be in Maven Central soon.

**Pull request merged**
