### PR TITLE
Added an empty settings.gradle so grgit could be used in composite build

### PR DESCRIPTION
**Pull request by donalhenry**

### CODE REVIEW

**Comment by ajoberstar** [comment]
Thanks!

**Comment by donalhenry** [comment]
Not related to this pull request, but the grgit plugin...

I've encountered a number of bugs and lack of features with jgit - all around cloning.  What would you think about allowing an option to exec "git clone" instead of calling the jgit clone?

**Comment by ajoberstar** [comment]
I wouldn't want to go down that road. Grgit is just meant to be a nicer facade over JGit, so it intentionally has the same bugs or lack of features. That's not ideal for all cases, but it greatly reduces the amount of code that has to be maintained in Grgit.

In your scenario, would it be easy enough to do the exec directly and only switch to Grgit once the repo is there?

**Comment by donalhenry** [comment]
Thanks for getting back.  Yes, I'll do the exec and then a grgit open on the local repo.  I really want to do shallow clones within our CD pipeline and JGit doesn't support this feature.

**Pull request merged**
