### PR TITLE
[WIP] Support JGit 5

### LINKED ISSUE #233: Upgrade to JGit 5

### PR DESCRIPTION
**Pull request by ajoberstar**
Switch off of methods removed in JGit 5.

This fixes #233.

### CODE REVIEW

**Comment by ajoberstar** [comment]
This should wait for the final version of JGit 5 to be released. This currently uses rc2.

**Comment by childnode** [comment]
regarding https://github.com/ajoberstar/gradle-git/issues/260 we will need an option for the behaviour in grgit, else users are not able to turn back to the old grgit/jgit behaviour, didn't we?

**Comment by ajoberstar** [comment]
@childnode Agreed. This does make me think this is going to be a breaking release, since there could be other behavior changes from the JGit upgrade.

**Comment by ajoberstar** [comment]
Closed in favor of #246.

**Pull request closed without merging**
